function supertitle(title,fontsz,color)

if nargin < 2
    fontsz = 15;
    color = 'k';
elseif nargin < 3
    color = 'k';
end

annotation('textbox', [0 0.97 1 0.03], ...
    'String', title, ...
    'Fontsize', fontsz, ...
    'EdgeColor', 'none', ...
    'Color', color, ...
    'HorizontalAlignment', 'center',...
    'Interpreter', 'latex');
end